import os

date = (input("What is the date? "))
line1 = (input("1/10: "))
line2 = (input("2/10: "))
line3 = (input("3/10: "))
line4 = (input("4/10: "))
line5 = (input("5/10: "))
line6 = (input("6/10: "))
line7 = (input("7/10: "))
line8 = (input("8/10: "))
line9 = (input("9/10: "))
line10 = (input("10/10: "))
a = (line1)
b = (line2)
c = (line3)
d = (line4)
e = (line5)
f = (line6)
g = (line7)
h = (line8)
i = (line9)
j = (line10)
k = ("------------------")
file = open("DIARY.docx", "w")
file.write(a + "\n" + b + "\n" + c + "\n" + d + "\n" + e + "\n" + f + "\n" + g + "\n" + h + "\n" + i + "\n" + j + "\n" + k + "\n")
file.close()
print("saved")
os.system("pause")
os.system("exit")
